# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "dduportal/boot2docker"

  config.vm.provider :virtualbox do |vb|

    config.vm.network "forwarded_port", guest: 3000, host: 3000

    vb.customize ["modifyvm", :id, "--memory", "2014"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]

  end

  config.vm.provision "shell", path: "provision.sh", run: "always"
end
